version: 2
updates:
  - package-ecosystem: 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    groups:
      eslint:
        patterns:
          - '*eslint*'
      remix:
        patterns:
          - '*remix*'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 18'
    open-pull-requests-limit: 5
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
