version: 2
updates:
  - package-ecosystem: 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    open-pull-requests-limit: 15
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 16'
    open-pull-requests-limit: 15
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
