name: 'Setup'
description: 'Common setup steps for all jobs'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - uses: nrwl/nx-set-shas@v3
    - run: npm i -g npm@9
      shell: bash
    - run: npm ci
      shell: bash
    - run: npx --no-install nx run-many --target=build --parallel=4
      shell: bash
