name: 'Setup'
description: 'Common setup steps for all jobs'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm i -g npm@9
      shell: bash
    - run: npm ci
      shell: bash
