env:
  es6: true
  node: true
extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react/recommended'
  - 'prettier/react'
parserOptions:
  ecmaFeatures:
    jsx: true
overrides:
  - files: ['!src/**/*.js']
    parserOptions:
      sourceType: script
  - files: ['gatsby-*.js']
    rules:
      no-restricted-syntax: off
plugins:
  - jsx-a11y
  - react
rules:
  import/no-unassigned-import:
    - error
    - allow:
        - '**/*.css'
        - '**/*.scss'
  require-jsdoc: off
  quotes:
    - error
    - single
settings:
  react:
    version: 'detect'
