env:
  es6: true
  node: true
extends:
  - "@ianwremmel/eslint-config-standard"
  - "plugin:react/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:react/recommended"
  - prettier
  - "prettier/react"
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - jsx-a11y
  - react
rules:
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  sort-imports:
  - off
  import/no-unassigned-import:
    - error
    - allow:
      - '**/*.css'
