env:
  es6: true
  node: true
extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/react'
  - 'plugin:jsx-a11y/recommended'
  - '@remix-run/eslint-config'
  - '@remix-run/eslint-config/node'
  - 'plugin:react/recommended'
  - 'prettier'

overrides:
  # make sure eslint lints all files
  - files:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'

  - extends:
      - 'plugin:@ianwremmel/ianwremmel/typescript'
    files:
      - '**/*.ts'
      - '**/*.tsx'
    rules:
      '@typescript-eslint/consistent-type-definitions':
        - error
        - interface
      no-shadow: off
      '@typescript-eslint/no-shadow': error
      no-use-before-define: off
      '@typescript-eslint/no-use-before-define':
        - error
        - classes: true
          functions: false
          variables: true

  - files: ['**/*.js']
    parserOptions:
      sourceType: script

  - files: ['server.js']
    parserOptions:
      sourceType: module

parserOptions:
  ecmaFeatures:
    jsx: true

plugins:
  - jsx-a11y
  - react

rules:
  import/no-unassigned-import:
    - error
    - allow:
        - '**/*.css'
        - '**/*.scss'
  require-jsdoc: off
  react/react-in-jsx-scope: off

settings:
  react:
    version: 'detect'
  linkComonents:
    - name: 'Link'
      linkAttribute: 'href'
