env:
  es6: true
  node: true
extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/react'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
overrides:
  - files: ['!src/**/*.js']
    parserOptions:
      sourceType: script
plugins:
  - jsx-a11y
  - react
rules:
  import/no-unassigned-import:
    - error
    - allow:
        - '**/*.css'
        - '**/*.scss'
  require-jsdoc: off
settings:
  react:
    version: 'detect'
  linkComonents:
    - name: 'Link'
      linkAttribute: 'href'
