env:
  es6: true
  node: true

extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'prettier'

ignorePatterns:
  - '!build'
  - '__generated__'

overrides:
  # make sure eslint lints all files
  - files:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mts'

  - extends:
      - 'plugin:@ianwremmel/ianwremmel/typescript'
    files:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mts'
    rules:
      '@typescript-eslint/consistent-type-definitions':
        - error
        - interface
      no-shadow: off
      '@typescript-eslint/no-shadow': error
      no-use-before-define: off
      '@typescript-eslint/no-use-before-define':
        - error
        - classes: true
          functions: false
          variables: true
      no-duplicate-imports: off

parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module

rules:
  compat/compat: off
  import/no-unassigned-import:
    - error
    - allow:
        - '**/*.css'
        - '**/*.scss'
  no-restricted-syntax: off
  require-jsdoc: off
