restore_cache: &restore_cache
  keys:
    # added the sequence number after node-modules for cache-busting purposes.
    # it seems the "Rebuild Without Cache" button ha disappeared.
    - node-modules-1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
    - node-modules-1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
    - node-modules-1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}

save_cache: &save_cache
  key: node-modules-1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
  paths:
    - node_modules

version: 2
jobs:
  lint:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - run: npm run lint
      - save_cache: *save_cache

workflows:
  version: 2
  build:
    jobs:
      - lint
