[build]
  command = "npm run build"
  publish = "public"
  environment = { NPM_VERSION = "8" }

[dev]
  command = "remix watch"
  port = 3000

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[redirects]]
  from = "/business-card"
  to = "/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
