[build]
command = "make all"
publish = "public"
environment = { NPM_VERSION = "9" }

[dev]
command = "remix watch"
port = 3000

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[redirects]]
from = "/business-card"
to = "/"
status = 302

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200
