#!/usr/bin/env bash

set -euo pipefail

set -x

trap stop_server EXIT

SERVER_PID=
start_server () {
  make storybook-static
  npx --no-install http-server storybook-static --port 6006 &
  SERVER_PID=$!
}

run_tests () {
  npx --no-install wait-on --timeout 10000 --verbose tcp:127.0.0.1:6006
  TARGET_URL=http://localhost:6006 npx test-storybook
}

stop_server () {
  kill $SERVER_PID
}

start_server
run_tests
