on: push
name: Validate
jobs:
  fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: ianwremmel/prevent-fixup-commits@v1.0.2

  nopush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: ianwremmel/prevent-nopush-commits@v1.0.3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run lint
        env:
          ESLINT_FORMAT_OPTIONS:
            '--format json-with-metadata --output-file reports/style/eslint.json'
          TSC_OPTIONS: '| tee reports/style/tsc.log'
      - uses: check-run-reporter/action@v2.7.1
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: ESLint
          report: 'reports/style/eslint.json'
      - uses: check-run-reporter/action@v2.7.1
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: TSC
          report: 'reports/style/tsc.log'
