on: push
name: Validate
jobs:
#  These actions are currently broken
#  fixup:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3.0.2
#        with:
#          fetch-depth: 0
#      - uses: ianwremmel/prevent-fixup-commits@v1.0.2
#
#  nopush:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3.0.2
#        with:
#          fetch-depth: 0
#      - uses: ianwremmel/prevent-nopush-commits@v1.0.3

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i -g npm@8
      - run: npm ci
      - uses: ./.github/setup-make
      - run: make chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - run: npx test-storybook
        env:
          # I'd love to get this constant part of this at runtime, but there
          # doesn't seem to be any way to do so.
          TARGET_URL: 'https://${{ github.ref_name }}--62911a8fe23893003a9b5d0a.chromatic.com'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i -g npm@8
      - run: npm ci
      - run: make app/root.css
      - run: npm run lint
        env:
          ESLINT_FORMAT_OPTIONS:
            '--format json-with-metadata --output-file reports/style/eslint.json'
          TSC_OPTIONS: '| tee reports/style/tsc.log'
      - uses: check-run-reporter/action@v2.11.1
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: ESLint
          report: 'reports/style/eslint.json'
      - uses: check-run-reporter/action@v2.11.1
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: TSC
          report: 'reports/style/tsc.log'
