on: push
name: Validate
jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup'
      - run: ./scripts/storybook-test-runner
      - uses: check-run-reporter/action@v2.12.0
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: Storybook Test Runner
          report: 'reports/junit/**/*.xml'

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup'
      - run: npm run chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup'
      - run: npm run lint
        env:
          ESLINT_FORMAT_OPTIONS:
            '--format json-with-metadata --output-file reports/style/eslint.json'
          TSC_OPTIONS: '| tee reports/style/tsc.log'
      - uses: check-run-reporter/action@v2.12.0
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: ESLint
          report: 'reports/style/eslint.json'
      - uses: check-run-reporter/action@v2.12.0
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: TSC
          report: 'reports/style/tsc.log'
