on: push
name: Validate
jobs:
  #  These actions are currently broken
  #  fixup:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4.1.1
  #        with:
  #          fetch-depth: 0
  #      - uses: ianwremmel/prevent-fixup-commits@v1.0.2
  #
  #  nopush:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4.1.1
  #        with:
  #          fetch-depth: 0
  #      - uses: ianwremmel/prevent-nopush-commits@v1.0.3

  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i -g npm@9
      - run: npm ci
      - uses: ./.github/setup-make
      - run: ./scripts/storybook-test-runner
      - uses: check-run-reporter/action@v2.12.0
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: Storybook Test Runner
          report: 'reports/junit/**/*.xml'

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i -g npm@9
      - run: npm ci
      - uses: ./.github/setup-make
      - run: make chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i -g npm@9
      - run: npm ci
      - run: make app/root.css
      - run: npm run lint
        env:
          ESLINT_FORMAT_OPTIONS:
            '--format json-with-metadata --output-file reports/style/eslint.json'
          TSC_OPTIONS: '| tee reports/style/tsc.log'
      - uses: check-run-reporter/action@v2.12.0
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: ESLint
          report: 'reports/style/eslint.json'
      - uses: check-run-reporter/action@v2.12.0
        if: ${{ always() }}
        with:
          token: '817ac479-0683-4242-be42-9f7b87ea2ed6'
          label: TSC
          report: 'reports/style/tsc.log'
